import type { ExamQuestion } from '../types';

/** Domain 1.0: Network Infrastructure and Connectivity. */
export const infrastructureQuestions: ExamQuestion[] = [
  {
    id: 'ipv4-hosts-27',
    domain: '1.0',
    objective: '1.3',
    prompt: 'How many addresses can be assigned to hosts in a /27 subnet?',
    correct: ['30'],
    wrong: ['32', '14', '62'],
    explain: 'A /27 leaves 5 host bits: 2^5 = 32 addresses, minus the network and broadcast addresses, gives 30 usable hosts.',
    labs: ['subnetting-hosts'],
  },
  {
    id: 'ipv4-broadcast-26',
    domain: '1.0',
    objective: '1.3',
    prompt: 'What is the broadcast address of the subnet that contains 172.16.45.70/26?',
    correct: ['172.16.45.127'],
    wrong: ['172.16.45.63', '172.16.45.128', '172.16.45.255'],
    explain: 'A /26 moves in blocks of 64 in the last octet: .0, .64, .128, .192. Host .70 sits in the .64 block, whose last address, .127, is the broadcast.',
    labs: ['subnetting-hosts'],
  },
  {
    id: 'ipv4-smallest-prefix',
    domain: '1.0',
    objective: '1.3',
    prompt: 'A VLAN needs room for 50 hosts. Which prefix length wastes the fewest addresses?',
    correct: ['/26'],
    wrong: ['/25', '/27', '/28'],
    explain: 'A /27 offers only 30 hosts. A /26 offers 62, the smallest block that fits 50.',
    labs: ['subnetting-hosts'],
  },
  {
    id: 'ipv4-mask-22',
    domain: '1.0',
    objective: '1.3',
    prompt: 'Which dotted-decimal mask matches a /22 prefix?',
    correct: ['255.255.252.0'],
    wrong: ['255.255.248.0', '255.255.254.0', '255.255.255.252'],
    explain: 'Twenty-two bits is 16 bits for the first two octets plus 6 in the third: 11111100 = 252.',
  },
  {
    id: 'ipv4-private',
    domain: '1.0',
    objective: '1.3',
    prompt: 'Which address is a private (RFC 1918) address?',
    correct: ['172.20.14.1'],
    wrong: ['172.32.1.1', '192.169.10.1', '11.0.0.1'],
    explain: 'The private ranges are 10.0.0.0/8, 172.16.0.0/12 (172.16.0.0 to 172.31.255.255) and 192.168.0.0/16. 172.32.x.x falls just outside the /12.',
    labs: ['nat-pat'],
  },
  {
    id: 'ipv4-gateway-outside',
    domain: '1.0',
    objective: '1.6',
    prompt: 'A PC is set to 10.1.1.200/25 with default gateway 10.1.1.1. It can reach hosts in its own subnet but nothing beyond. What is wrong?',
    correct: ['The gateway is not in the PC’s subnet'],
    wrong: ['The /25 mask is invalid for a 10.x address', 'The PC needs a DNS server to leave the subnet', '10.1.1.200 is the broadcast address of its subnet'],
    explain: '10.1.1.200/25 belongs to 10.1.1.128/25 (hosts .129 to .254). The gateway 10.1.1.1 is in the other half, so the PC cannot ARP for it.',
    labs: ['fix-the-office'],
  },
  {
    id: 'ipv4-class-b',
    domain: '1.0',
    objective: '1.3',
    prompt: 'Which first-octet range belongs to classful Class B addresses?',
    correct: ['128 to 191'],
    wrong: ['1 to 126', '192 to 223', '224 to 239'],
    explain: 'Class A is 1 to 126, Class B 128 to 191, Class C 192 to 223, and Class D (multicast) 224 to 239.',
  },
  {
    id: 'apipa',
    domain: '1.0',
    objective: '1.7',
    prompt: 'A Windows PC set to obtain an address automatically shows 169.254.33.7. What does that tell you?',
    correct: ['It never got a reply from a DHCP server'],
    wrong: ['The DHCP server leased it a link-local address on purpose', 'It has a duplicate address on the LAN', 'Its DNS server is unreachable'],
    explain: '169.254.0.0/16 is APIPA. Windows picks one when DHCP discovery fails, so look at the path to the DHCP server or the relay.',
    labs: ['dhcp-server', 'wireless-troubleshoot'],
  },
  {
    id: 'dhcp-dora',
    domain: '1.0',
    objective: '1.7',
    prompt: 'In what order are the four DHCP messages exchanged when a client first gets an address?',
    correct: ['Discover, Offer, Request, Acknowledge'],
    wrong: ['Request, Offer, Discover, Acknowledge', 'Discover, Request, Offer, Acknowledge', 'Offer, Discover, Acknowledge, Request'],
    explain: 'DORA: the client broadcasts a Discover, servers Offer, the client Requests one offer, and that server Acknowledges.',
    labs: ['dhcp-server'],
  },
  {
    id: 'dhcp-relay',
    domain: '1.0',
    objective: '1.7',
    prompt: 'Clients in VLAN 20 must get addresses from a DHCP server in another subnet. What do you configure on the router interface that is the clients’ gateway?',
    correct: ['ip helper-address followed by the server’s address'],
    wrong: ['ip dhcp pool on that interface', 'ip dhcp snooping trust', 'ip address dhcp'],
    explain: 'DHCP Discovers are broadcasts and routers do not forward broadcasts. ip helper-address makes the interface relay them to the server as unicast.',
    labs: ['dhcp-relay'],
  },
  {
    id: 'dhcp-exclude',
    domain: '1.0',
    objective: '1.7',
    prompt: 'Which command stops a Cisco DHCP server from leasing 192.168.1.1 to 192.168.1.10?',
    correct: ['ip dhcp excluded-address 192.168.1.1 192.168.1.10 (global configuration)'],
    wrong: ['excluded-address 192.168.1.1 192.168.1.10 (inside the pool)', 'no network 192.168.1.1 192.168.1.10', 'ip dhcp reserve 192.168.1.1 192.168.1.10'],
    explain: 'Exclusions are global, not part of the pool, and should be entered before the pool starts leasing.',
    labs: ['dhcp-server'],
  },
  {
    id: 'dhcp-ports',
    domain: '1.0',
    objective: '1.7',
    prompt: 'Which transport and ports does DHCP for IPv4 use?',
    correct: ['UDP 67 on the server and UDP 68 on the client'],
    wrong: ['TCP 67 on the server and TCP 68 on the client', 'UDP 68 on the server and UDP 67 on the client', 'UDP 546 and 547'],
    explain: 'DHCPv4 servers listen on UDP 67 and clients on UDP 68. UDP 546 and 547 are DHCPv6.',
  },
  {
    id: 'dhcp-renew-windows',
    domain: '1.0',
    objective: '1.6',
    prompt: 'Which Windows command makes a PC ask its DHCP server for a lease again?',
    correct: ['ipconfig /renew'],
    wrong: ['ipconfig /release', 'ipconfig /flushdns', 'arp -d *'],
    explain: '/release gives the lease back; /renew starts the request. /flushdns and arp -d clear caches but do not touch the address.',
  },
  {
    id: 'client-linux-ip',
    domain: '1.0',
    objective: '1.6',
    prompt: 'On a Linux host, which command shows the IP addresses assigned to its interfaces?',
    correct: ['ip address show'],
    wrong: ['ipconfig /all', 'show ip interface brief', 'netsh interface ip show config'],
    explain: 'ip address (or the older ifconfig) is the Linux tool. ipconfig and netsh are Windows; show ip interface brief is Cisco IOS.',
  },
  {
    id: 'ipv6-compress',
    domain: '1.0',
    objective: '1.4',
    prompt: 'What is the shortest valid way to write 2001:0db8:0000:0000:0000:ff00:0042:8329?',
    correct: ['2001:db8::ff00:42:8329'],
    wrong: ['2001:db8::ff:42:8329', '2001:db8:::ff00:42:8329', '2001:db8::ff00::42:8329'],
    explain: 'Drop leading zeros in each quartet (0db8 to db8, 0042 to 42) and replace one run of all-zero quartets with ::. Trailing zeros (ff00) stay, and :: may appear only once.',
    labs: ['ipv6-addressing'],
  },
  {
    id: 'ipv6-eui64',
    domain: '1.0',
    objective: '1.4',
    prompt: 'A router interface has MAC 0011.2233.4455 and is configured with ipv6 address 2001:db8:1:1::/64 eui-64. Which address does it build?',
    correct: ['2001:db8:1:1:211:22ff:fe33:4455'],
    wrong: ['2001:db8:1:1:11:22ff:fe33:4455', '2001:db8:1:1:211:2233:fffe:4455', '2001:db8:1:1:211:22fe:ff33:4455'],
    explain: 'Split the MAC in half, insert FFFE in the middle (0011.22FF.FE33.4455), then flip the 7th bit of the first byte: 00 becomes 02.',
    labs: ['ipv6-addressing'],
  },
  {
    id: 'ipv6-link-local',
    domain: '1.0',
    objective: '1.4',
    prompt: 'Which prefix do IPv6 link-local addresses come from?',
    correct: ['FE80::/10'],
    wrong: ['FC00::/7', 'FF02::/16', '2000::/3'],
    explain: 'Link-local is FE80::/10 and never routed. FC00::/7 is unique local, FF02::/16 link-scope multicast, and 2000::/3 global unicast.',
    labs: ['ipv6-addressing'],
  },
  {
    id: 'ipv6-ula',
    domain: '1.0',
    objective: '1.4',
    prompt: 'Which IPv6 addresses play the role that RFC 1918 private addresses play in IPv4?',
    correct: ['Unique local addresses in FC00::/7'],
    wrong: ['Link-local addresses in FE80::/10', 'Global unicast addresses in 2000::/3', 'Anycast addresses in FF00::/8'],
    explain: 'Unique local addresses (in practice FDxx::) are routable inside an organisation but dropped by ISPs, like private IPv4.',
  },
  {
    id: 'ipv6-ndp',
    domain: '1.0',
    objective: '1.4',
    prompt: 'IPv6 has no ARP. Which messages does a host use instead to learn a neighbor’s MAC address?',
    correct: ['ICMPv6 Neighbor Solicitation and Neighbor Advertisement'],
    wrong: ['ICMPv6 Router Solicitation and Router Advertisement', 'DHCPv6 Solicit and Advertise', 'Broadcast ARP over IPv6'],
    explain: 'NDP replaces ARP: an NS goes to the target’s solicited-node multicast address and the target answers with an NA.',
  },
  {
    id: 'ipv6-slaac',
    domain: '1.0',
    objective: '1.4',
    prompt: 'A host set for SLAAC has only a link-local address. Where should it have learned its global prefix from?',
    correct: ['A Router Advertisement from a router on its link'],
    wrong: ['A DHCPv6 server lease', 'Its own MAC address', 'A Neighbor Advertisement from its gateway'],
    explain: 'SLAAC hosts take the /64 prefix from Router Advertisements. No RA (for example, a router without ipv6 unicast-routing) means no global address.',
    labs: ['ipv6-troubleshoot'],
  },
  {
    id: 'ipv6-multicast-all-nodes',
    domain: '1.0',
    objective: '1.4',
    prompt: 'Which IPv6 address reaches every node on the local link, much like an IPv4 broadcast?',
    correct: ['FF02::1'],
    wrong: ['FF02::2', 'FE80::1', '::1'],
    explain: 'FF02::1 is all nodes, FF02::2 all routers. ::1 is loopback; IPv6 has no broadcast.',
  },
  {
    id: 'cable-late-collisions',
    domain: '1.0',
    objective: '1.1',
    prompt: 'show interfaces on one end of a link shows late collisions climbing. What is the most likely cause?',
    correct: ['A duplex mismatch'],
    wrong: ['A speed mismatch', 'A native VLAN mismatch', 'An MTU mismatch'],
    explain: 'The half-duplex side sees late collisions while the full-duplex side logs CRC errors and runts. A speed mismatch would keep the link down instead.',
  },
  {
    id: 'cable-copper-distance',
    domain: '1.0',
    objective: '1.1',
    prompt: 'What is the maximum segment length for 1000BASE-T over Cat 5e or Cat 6 copper?',
    correct: ['100 metres'],
    wrong: ['55 metres', '185 metres', '500 metres'],
    explain: 'Twisted-pair Ethernet up to 1 Gbps is rated for 100 m. Longer runs need fiber or a switch in between.',
  },
  {
    id: 'cable-fiber',
    domain: '1.0',
    objective: '1.1',
    prompt: 'Which statement about fiber is true?',
    correct: ['Single-mode fiber has a narrower core and reaches farther than multimode'],
    wrong: ['Multimode fiber reaches farther because it carries more modes', 'Single-mode fiber uses cheaper LED transmitters', 'Fiber is limited to 100 metres like copper'],
    explain: 'Single-mode uses a small core and lasers for kilometres of reach; multimode has a wider core, cheaper optics and shorter reach.',
  },
  {
    id: 'cable-crossover',
    domain: '1.0',
    objective: '1.1',
    prompt: 'Two older switches without Auto MDI-X are cabled together with copper. Which cable brings the link up?',
    correct: ['A crossover cable'],
    wrong: ['A straight-through cable', 'A rollover cable', 'A serial DCE cable'],
    explain: 'Like devices (switch to switch, PC to PC) need a crossover; unlike devices (PC to switch) use straight-through. Auto MDI-X removes the issue on modern gear.',
  },
  {
    id: 'interface-admin-down',
    domain: '1.0',
    objective: '1.1',
    prompt: 'show ip interface brief lists Gi0/1 as "administratively down / down". What fixes it?',
    correct: ['no shutdown on the interface'],
    wrong: ['Replacing the cable', 'Matching the duplex on both ends', 'Adding an IP address'],
    explain: 'Administratively down means the interface is shut down in the configuration. Router interfaces start that way.',
    labs: ['router-basics'],
  },
  {
    id: 'virt-type1',
    domain: '1.0',
    objective: '1.2',
    prompt: 'Which describes a Type 1 hypervisor such as VMware ESXi?',
    correct: ['It runs directly on the server hardware'],
    wrong: ['It runs as an application on a desktop operating system', 'It shares one kernel among all its workloads', 'It only runs containers'],
    explain: 'Type 1 (bare-metal) hypervisors sit on the hardware and suit data centres. Type 2 hypervisors, like VirtualBox, run on top of a host OS.',
  },
  {
    id: 'virt-containers',
    domain: '1.0',
    objective: '1.2',
    prompt: 'What is the key difference between containers and virtual machines?',
    correct: ['Containers share the host operating system kernel; each VM runs its own guest OS'],
    wrong: ['Containers need a Type 1 hypervisor; VMs do not', 'VMs start faster and use less memory than containers', 'Containers cannot be moved between hosts'],
    explain: 'Because containers share the host kernel they are small and fast to start, but a host OS crash takes every container with it.',
  },
  {
    id: 'virt-saas',
    domain: '1.0',
    objective: '1.2',
    prompt: 'A company uses Microsoft 365 in the browser and manages nothing but user settings. Which cloud service model is that?',
    correct: ['Software as a Service'],
    wrong: ['Platform as a Service', 'Infrastructure as a Service', 'Private cloud'],
    explain: 'SaaS delivers finished applications. PaaS hosts your own code; IaaS rents virtual servers, storage and networks. Private cloud is a deployment model, not a service model.',
  },
  {
    id: 'wifi-24-channels',
    domain: '1.0',
    objective: '1.5',
    prompt: 'Which 2.4 GHz channels should neighbouring APs use so that none of them overlap?',
    correct: ['1, 6 and 11'],
    wrong: ['1, 2 and 3', '1, 5 and 9', '36, 40 and 44'],
    explain: '2.4 GHz channels are 5 MHz apart but about 20 MHz wide, so only 1, 6 and 11 avoid each other in most regions. 36, 40 and 44 are 5 GHz channels.',
    labs: ['wireless-channels'],
  },
  {
    id: 'wifi-5ghz',
    domain: '1.0',
    objective: '1.5',
    prompt: 'Compared with 2.4 GHz, what is true of the 5 GHz band?',
    correct: ['More non-overlapping channels but shorter range through walls'],
    wrong: ['Longer range but fewer channels', 'It does not support 802.11ac or 802.11ax', 'It suffers more from microwave oven interference'],
    explain: 'Higher frequencies are absorbed more by obstacles, so range drops, but 5 GHz offers many more 20 MHz channels. Microwave ovens interfere with 2.4 GHz.',
    labs: ['wireless-channels'],
  },
  {
    id: 'wifi-wpa3',
    domain: '1.0',
    objective: '1.5',
    prompt: 'Which security mode replaces the pre-shared key handshake with SAE (Simultaneous Authentication of Equals)?',
    correct: ['WPA3-Personal'],
    wrong: ['WPA2-Personal', 'WPA2-Enterprise', 'WEP'],
    explain: 'WPA3-Personal uses SAE, which resists offline dictionary attacks on the passphrase. WPA2-Personal uses a PSK four-way handshake.',
    labs: ['wlan-enterprise-guest'],
  },
  {
    id: 'wifi-enterprise',
    domain: '1.0',
    objective: '1.5',
    prompt: 'What does WPA2-Enterprise use to authenticate each user?',
    correct: ['802.1X with an authentication server such as RADIUS'],
    wrong: ['One passphrase shared by every user', 'The client’s MAC address', 'A web portal with no encryption'],
    explain: 'Enterprise mode authenticates each user with EAP over 802.1X, checked by a RADIUS server, so users can be revoked individually.',
    labs: ['wlan-enterprise-guest'],
  },
  {
    id: 'tcp-handshake',
    domain: '1.0',
    objective: '1.6',
    prompt: 'Which messages make up the TCP three-way handshake, in order?',
    correct: ['SYN, SYN-ACK, ACK'],
    wrong: ['SYN, ACK, FIN', 'ACK, SYN, SYN-ACK', 'SYN, SYN, ACK'],
    explain: 'The client sends SYN, the server answers SYN-ACK, and the client confirms with ACK.',
  },
  {
    id: 'udp-apps',
    domain: '1.0',
    objective: '1.6',
    prompt: 'Which application protocol runs over UDP?',
    correct: ['TFTP'],
    wrong: ['FTP', 'SSH', 'HTTPS'],
    explain: 'TFTP uses UDP 69 and handles its own acknowledgements. FTP, SSH and HTTPS all use TCP.',
    labs: ['config-backup'],
  },
  {
    id: 'ipv4-ttl',
    domain: '1.0',
    objective: '1.3',
    prompt: 'What does a router do with the IPv4 TTL field when it forwards a packet?',
    correct: ['Decrements it by 1 and drops the packet if it reaches 0'],
    wrong: ['Resets it to 255', 'Increments it by 1 to count hops', 'Leaves it unchanged'],
    explain: 'TTL stops routing loops from circulating packets forever. Traceroute relies on the ICMP Time Exceeded messages routers send when it hits 0.',
  },
  {
    id: 'packet-dst-mac',
    domain: '1.0',
    objective: '1.6',
    prompt: 'PC1 sends a packet to a server in another subnet. What destination MAC address does the frame leaving PC1 carry?',
    correct: ['The MAC address of PC1’s default gateway'],
    wrong: ['The server’s MAC address', 'The broadcast address FFFF.FFFF.FFFF', 'The MAC address of the switch PC1 is connected to'],
    explain: 'The IP addresses stay end to end, but each Layer 2 hop is rewritten. A remote destination means the first frame goes to the gateway.',
    labs: ['router-basics'],
  },
  {
    id: 'spine-leaf',
    domain: '1.0',
    objective: '1.2',
    prompt: 'Which rule describes a spine-leaf data centre design?',
    correct: ['Every leaf switch connects to every spine switch, and servers connect only to leaves'],
    wrong: ['Spine switches connect to each other in a full mesh', 'Leaf switches connect to each other for redundancy', 'Servers connect to spines for the lowest latency'],
    explain: 'Any server is the same number of hops from any other, which suits heavy east-west traffic between virtual machines.',
  },
];
