import type { ExamQuestion } from '../types';

/** Domain 5.0: AI, and Network Operations and Management. */
export const operationsQuestions: ExamQuestion[] = [
  {
    id: 'agentic-ai',
    domain: '5.0',
    objective: '5.1',
    prompt: 'What sets an agentic AI system apart from a generative AI chatbot in network operations?',
    correct: ['It can plan multi-step tasks and act on them with tools, such as running show commands, toward a goal'],
    wrong: ['It only answers questions in natural language', 'It replaces routing protocols with machine learning', 'It needs no permissions because it only reads data'],
    explain: 'An agent pursues a goal by choosing and calling tools in a loop. Because it can act, it needs scoped permissions and human oversight.',
  },
  {
    id: 'agentic-ai-oversight',
    domain: '5.0',
    objective: '5.1',
    prompt: 'An AI agent diagnoses an outage and proposes a configuration change on a production core switch. What is the sound practice?',
    correct: ['Review and approve the change, and its rollback, before it is applied'],
    wrong: ['Let the agent apply it at once, since it found the fault', 'Apply it, then ask the agent to check its own work', 'Ignore the proposal; AI output is never useful'],
    explain: 'Agents speed up diagnosis, but changes to production need a human in the loop, validation against the evidence and a way back.',
  },
  {
    id: 'prompt-data-classification',
    domain: '5.0',
    objective: '5.2',
    prompt: 'You want a public generative AI service to explain a router’s running-config. What should you do first?',
    correct: ['Remove secrets and internal details the data classification policy does not allow to leave the company'],
    wrong: ['Paste it as is so the answer is accurate', 'Add your enable secret so the AI can log in', 'Convert it to JSON'],
    explain: 'Prompts sent to an external service leave your control. Passwords, keys, SNMP communities and internal addressing are often restricted data.',
  },
  {
    id: 'prompt-persona',
    domain: '5.0',
    objective: '5.2',
    prompt: 'A prompt begins "You are a senior network engineer reviewing changes for a bank." Which prompt component is that?',
    correct: ['Persona'],
    wrong: ['Output format', 'Data classification', 'Context window'],
    explain: 'A persona sets the role and expertise the model should answer from. Instructions say what to do; output format says how to present it.',
  },
  {
    id: 'prompt-output-format',
    domain: '5.0',
    objective: '5.2',
    prompt: 'Which prompt line is an output format instruction?',
    correct: ['"Answer as a table with columns: interface, status, problem."'],
    wrong: ['"You are a Cisco TAC engineer."', '"Here is the output of show ip ospf neighbor."', '"Find why R2 has no OSPF neighbors."'],
    explain: 'The other lines are a persona, supplied data and the instruction. Asking for a fixed format makes the answer easy to check or feed into a tool.',
  },
  {
    id: 'sdn-northbound',
    domain: '5.0',
    objective: '5.3',
    prompt: 'In controller-based networking, what does the northbound interface connect?',
    correct: ['The controller to applications and scripts, usually through a REST API'],
    wrong: ['The controller to the network devices it manages', 'Access switches to distribution switches', 'Two controllers in a cluster'],
    explain: 'Southbound interfaces (NETCONF, OpenFlow, CLI over SSH) reach the devices; northbound APIs let apps and automation talk to the controller.',
    labs: ['restconf-api'],
  },
  {
    id: 'mgmt-approaches',
    domain: '5.0',
    objective: '5.3',
    prompt: 'A team stores every device configuration as templates in Git and applies changes only through a pipeline after review. Which management approach is this?',
    correct: ['Infrastructure as code'],
    wrong: ['Device-based management', 'Cloud-based management', 'Out-of-band management'],
    explain: 'IaC treats configuration as versioned, reviewable code applied by automation, so changes are repeatable and auditable. Device-based means logging in to each box.',
    labs: ['ansible-playbook'],
  },
  {
    id: 'mgmt-cloud',
    domain: '5.0',
    objective: '5.3',
    prompt: 'APs and switches at fifty branches are configured and monitored from a vendor-hosted web dashboard. Which approach is that?',
    correct: ['Cloud-based management'],
    wrong: ['Device-based management', 'Infrastructure as code', 'Controller-less autonomous management'],
    explain: 'Cloud-managed devices (Meraki, for example) call home to a hosted controller, so no on-site controller is needed.',
  },
  {
    id: 'ansible-agentless',
    domain: '5.0',
    objective: '5.5',
    prompt: 'Which statement about Ansible is true?',
    correct: ['It is agentless and pushes changes over SSH using YAML playbooks'],
    wrong: ['It needs an agent installed on every router', 'Devices pull their configuration from it on a schedule', 'Its playbooks are written in Ruby'],
    explain: 'Ansible needs only SSH (or an API) on the managed device. Puppet and Chef traditionally use agents and a pull model.',
    labs: ['ansible-playbook'],
  },
  {
    id: 'ansible-inventory',
    domain: '5.0',
    objective: '5.5',
    prompt: 'In Ansible, what does the inventory file define?',
    correct: ['The managed hosts and the groups they belong to'],
    wrong: ['The tasks to run, in order', 'The Python modules to install', 'The commit history of the configurations'],
    explain: 'The inventory lists hosts and groups (with variables); a playbook maps tasks onto hosts from it.',
    labs: ['ansible-playbook'],
  },
  {
    id: 'rest-verbs',
    domain: '5.0',
    objective: '5.5',
    prompt: 'Which HTTP method does a RESTCONF client use to read a device’s interface configuration?',
    correct: ['GET'],
    wrong: ['POST', 'PUT', 'DELETE'],
    explain: 'GET reads, POST creates, PUT replaces, PATCH updates part of a resource and DELETE removes it.',
    labs: ['restconf-api'],
  },
  {
    id: 'restconf-transport',
    domain: '5.0',
    objective: '5.3',
    prompt: 'What does RESTCONF need enabled on an IOS XE router?',
    correct: ['The HTTPS server and the restconf command'],
    wrong: ['SNMPv3 and a trap host', 'Telnet on the VTY lines', 'An Ansible inventory on the router'],
    explain: 'RESTCONF runs over HTTPS and exposes YANG-modelled data as JSON or XML.',
    labs: ['restconf-api'],
  },
  {
    id: 'snmp-ports',
    domain: '5.0',
    objective: '5.4',
    prompt: 'Which ports does SNMP use?',
    correct: ['Agents listen on UDP 161; managers receive traps on UDP 162'],
    wrong: ['Agents listen on TCP 161; traps go to TCP 162', 'UDP 514 for everything', 'UDP 162 on agents; UDP 161 on managers'],
    explain: 'The NMS polls agents on 161 (Get, Set) and agents send unsolicited Traps and Informs to the NMS on 162.',
    labs: ['snmp-v2c-traps'],
  },
  {
    id: 'snmp-v3',
    domain: '5.0',
    objective: '5.4',
    prompt: 'Which SNMP version and level gives both authentication and encryption?',
    correct: ['SNMPv3 with authPriv'],
    wrong: ['SNMPv2c with a read-only community', 'SNMPv3 with authNoPriv', 'SNMPv1 with a read-write community'],
    explain: 'v1 and v2c send community strings in clear text. v3 adds users: noAuthNoPriv, authNoPriv (integrity) and authPriv (integrity and encryption).',
    labs: ['snmpv3-secure'],
  },
  {
    id: 'snmp-inform',
    domain: '5.0',
    objective: '5.4',
    prompt: 'What is the difference between an SNMP Trap and an Inform?',
    correct: ['The manager acknowledges an Inform, so the agent can resend it; a Trap is not acknowledged'],
    wrong: ['Informs are sent by the manager to the agent', 'Traps are encrypted and Informs are not', 'Informs read values and Traps write them'],
    explain: 'Both are unsolicited messages from the agent. Gets read values, Sets write them.',
    labs: ['snmp-v2c-traps'],
  },
  {
    id: 'snmp-mib',
    domain: '5.0',
    objective: '5.4',
    prompt: 'What identifies an individual variable, such as sysName, that SNMP can read?',
    correct: ['An OID in the MIB'],
    wrong: ['A community string', 'A syslog facility', 'A YANG module name'],
    explain: 'The Management Information Base organises variables in a tree; each has an object identifier such as 1.3.6.1.2.1.1.5.0 for sysName.',
    labs: ['snmp-v2c-traps'],
  },
  {
    id: 'syslog-levels',
    domain: '5.0',
    objective: '5.6',
    prompt: 'Which syslog severity level is "warning"?',
    correct: ['4'],
    wrong: ['2', '5', '6'],
    explain: '0 emergency, 1 alert, 2 critical, 3 error, 4 warning, 5 notification, 6 informational, 7 debugging. Lower is more severe.',
    labs: ['syslog-read'],
  },
  {
    id: 'syslog-buffered',
    domain: '5.0',
    objective: '5.6',
    prompt: 'You configure logging buffered 5. Which messages are kept in the buffer?',
    correct: ['Severities 0 to 5'],
    wrong: ['Only severity 5', 'Severities 5 to 7', 'Severities 0 to 4'],
    explain: 'A logging level includes that level and everything more severe (lower numbers).',
    labs: ['syslog-read'],
  },
  {
    id: 'syslog-format',
    domain: '5.0',
    objective: '5.6',
    prompt: 'In the message below, what are LINEPROTO and 5?',
    exhibit: '*Oct  4 09:14:02.511: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet0/1, changed state to down',
    correct: ['The facility and the severity (notification)'],
    wrong: ['The severity and the facility', 'The mnemonic and the sequence number', 'The process name and the CPU usage'],
    explain: 'The format is %FACILITY-SEVERITY-MNEMONIC: description. UPDOWN is the mnemonic. The timestamp needs service timestamps log datetime.',
    labs: ['syslog-read'],
  },
  {
    id: 'syslog-server',
    domain: '5.0',
    objective: '5.6',
    prompt: 'Which two statements about syslog on Cisco IOS are true? (Choose two.)',
    correct: ['Messages sent to a remote syslog server use UDP port 514', 'Console logging is on by default, so messages appear on the console line'],
    wrong: ['Syslog lets an NMS change device settings', 'Messages are only kept if logging buffered is configured', 'Syslog servers poll devices for messages every 60 seconds'],
    explain: 'Devices push syslog to servers on UDP 514 and log to the console by default. Syslog is for reporting events; SNMP Set is what changes settings.',
    labs: ['syslog-read'],
  },
  {
    id: 'ntp-stratum',
    domain: '5.0',
    objective: '5.6',
    prompt: 'R1 synchronises to an NTP server at stratum 2. What stratum does R1 report?',
    correct: ['3'],
    wrong: ['2', '1', '16'],
    explain: 'Each hop away from the reference clock adds one. Stratum 16 means unsynchronised; ntp master defaults to stratum 8.',
    labs: ['ntp-clock'],
  },
  {
    id: 'ntp-why',
    domain: '5.0',
    objective: '5.6',
    prompt: 'Why should every device in the network synchronise its clock with NTP?',
    correct: ['So log timestamps line up when you correlate events across devices'],
    wrong: ['So routing protocols can converge', 'Because SSH refuses connections without NTP', 'So DHCP leases never expire'],
    explain: 'Accurate, consistent time makes syslog useful for troubleshooting and audits, and is needed for certificate checks.',
    labs: ['ntp-clock'],
  },
];
