import type { ExamQuestion } from '../types';

const TABLE = `Gateway of last resort is 203.0.113.1 to network 0.0.0.0

S*    0.0.0.0/0 [1/0] via 203.0.113.1
      10.0.0.0/8 is variably subnetted, 4 subnets, 3 masks
S        10.0.0.0/8 [1/0] via 192.168.12.2
O        10.1.0.0/16 [110/20] via 192.168.13.3, GigabitEthernet0/1
O        10.1.1.0/24 [110/30] via 192.168.14.4, GigabitEthernet0/2
D        10.1.1.0/25 [90/3072] via 192.168.15.5, GigabitEthernet0/3`;

/** Domain 3.0: IP Routing. */
export const routingQuestions: ExamQuestion[] = [
  {
    id: 'lpm-24',
    domain: '3.0',
    objective: '3.1',
    prompt: 'R1 has the routing table shown. Where does it send a packet for 10.1.1.200?',
    exhibit: TABLE,
    correct: ['192.168.14.4'],
    wrong: ['192.168.15.5', '192.168.13.3', '192.168.12.2'],
    explain: '10.1.1.200 is outside 10.1.1.0/25 (.0 to .127), so the longest matching prefix is 10.1.1.0/24 via 192.168.14.4.',
    labs: ['static-routing'],
  },
  {
    id: 'lpm-25',
    domain: '3.0',
    objective: '3.1',
    prompt: 'R1 has the routing table shown. Where does it send a packet for 10.1.1.20?',
    exhibit: TABLE,
    correct: ['192.168.15.5'],
    wrong: ['192.168.14.4', '192.168.13.3', '203.0.113.1'],
    explain: 'Longest prefix wins before administrative distance is considered: the EIGRP /25 is more specific than the OSPF /24.',
  },
  {
    id: 'lpm-default',
    domain: '3.0',
    objective: '3.1',
    prompt: 'R1 has the routing table shown. Where does it send a packet for 172.16.5.5?',
    exhibit: TABLE,
    correct: ['203.0.113.1, using the default route'],
    wrong: ['192.168.12.2, using the 10.0.0.0/8 route', 'Nowhere: it drops the packet', 'Out every interface'],
    explain: 'Nothing but 0.0.0.0/0 matches 172.16.5.5, so the gateway of last resort is used.',
    labs: ['default-route'],
  },
  {
    id: 'route-metric-brackets',
    domain: '3.0',
    objective: '3.1',
    prompt: 'In the entry "O 10.1.0.0/16 [110/20] via 192.168.13.3", what do 110 and 20 mean?',
    correct: ['110 is the administrative distance and 20 is the OSPF cost'],
    wrong: ['110 is the cost and 20 is the administrative distance', '110 is the process ID and 20 is the area', '110 is the hop count and 20 is the age in seconds'],
    explain: 'Routing table brackets are [AD/metric]. AD compares sources; the metric compares paths within one protocol.',
    labs: ['ospf-single-area'],
  },
  {
    id: 'ad-values',
    domain: '3.0',
    objective: '3.1',
    prompt: 'R1 learns 10.5.0.0/16 from both OSPF and EIGRP. Which route does it install, and why?',
    correct: ['The EIGRP route, because its administrative distance (90) is lower than OSPF’s (110)'],
    wrong: ['The OSPF route, because its AD (110) is higher', 'Whichever has the lower metric', 'Both, load-balancing between them'],
    explain: 'For the same prefix, the lowest AD wins. Metrics from different protocols are not comparable. Defaults: connected 0, static 1, eBGP 20, EIGRP 90, OSPF 110, RIP 120.',
  },
  {
    id: 'connected-local',
    domain: '3.0',
    objective: '3.1',
    prompt: 'You configure ip address 192.168.1.1 255.255.255.0 on G0/0 and bring it up. Which routes appear?',
    correct: ['C 192.168.1.0/24 and L 192.168.1.1/32'],
    wrong: ['C 192.168.1.1/24 only', 'S 192.168.1.0/24 and C 192.168.1.1/32', 'L 192.168.1.0/24 only'],
    explain: 'Every up interface with an address adds a connected route for its subnet and a local /32 host route for its own address.',
    labs: ['router-basics'],
  },
  {
    id: 'static-default',
    domain: '3.0',
    objective: '3.2',
    prompt: 'Which command gives a branch router a default route to its ISP at 203.0.113.1?',
    correct: ['ip route 0.0.0.0 0.0.0.0 203.0.113.1'],
    wrong: ['ip route 255.255.255.255 0.0.0.0 203.0.113.1', 'ip default-gateway 203.0.113.1', 'ip route 0.0.0.0 255.255.255.255 203.0.113.1'],
    explain: 'A default route matches everything: network 0.0.0.0 with mask 0.0.0.0. ip default-gateway is for hosts and Layer 2 switches that do not route.',
    labs: ['default-route'],
  },
  {
    id: 'floating-static',
    domain: '3.0',
    objective: '3.2',
    prompt: 'R1 learns 10.2.0.0/16 by OSPF over its primary link. You want a static route over a backup link that is used only if OSPF loses the route. What makes it a floating static?',
    correct: ['Give it an administrative distance above 110, for example 115'],
    wrong: ['Give it an administrative distance of 1', 'Give it a longer prefix, such as /24', 'Use the permanent keyword'],
    explain: 'With AD 115 the static loses to OSPF (110) while OSPF has the route and is installed only when it disappears. A longer prefix would always win.',
    labs: ['floating-static'],
  },
  {
    id: 'host-route',
    domain: '3.0',
    objective: '3.2',
    prompt: 'Which prefix lengths does a host route use?',
    correct: ['/32 for IPv4 and /128 for IPv6'],
    wrong: ['/24 for IPv4 and /64 for IPv6', '/0 for both', '/30 for IPv4 and /127 for IPv6'],
    explain: 'A host route matches exactly one address, so every bit is network bits.',
  },
  {
    id: 'static-recursive',
    domain: '3.0',
    objective: '3.2',
    prompt: 'Which kind of static route names only the next-hop address, so the router must look that address up to find the exit interface?',
    correct: ['A recursive static route'],
    wrong: ['A directly attached static route', 'A fully specified static route', 'A floating static route'],
    explain: 'Recursive routes give just the next hop; directly attached give just the interface; fully specified give both.',
    labs: ['static-routing'],
  },
  {
    id: 'ipv6-static-link-local',
    domain: '3.0',
    objective: '3.2',
    prompt: 'You write an IPv6 static route whose next hop is the neighbor’s link-local address FE80::2. What else must the command include?',
    correct: ['The exit interface'],
    wrong: ['An administrative distance', 'The eui-64 keyword', 'Nothing else'],
    explain: 'The same link-local address can exist on every link, so the router needs the interface to know which link: ipv6 route 2001:db8:3::/64 g0/0 fe80::2.',
    labs: ['ipv6-static-routing'],
  },
  {
    id: 'ipv6-unicast-routing',
    domain: '3.0',
    objective: '3.2',
    prompt: 'A router has IPv6 addresses on two interfaces, but hosts on one LAN cannot reach the other and get no Router Advertisements. What is missing?',
    correct: ['ipv6 unicast-routing'],
    wrong: ['ipv6 enable on the loopback', 'ip routing', 'A default route ::/0'],
    explain: 'IPv6 forwarding (and sending RAs) is off on IOS routers until ipv6 unicast-routing is configured.',
    labs: ['ipv6-static-routing', 'ipv6-troubleshoot'],
  },
  {
    id: 'ospf-link-state',
    domain: '3.0',
    objective: '3.3',
    prompt: 'How does OSPF build its routing table?',
    correct: ['Each router floods LSAs, builds the same link-state database and runs SPF (Dijkstra) on it'],
    wrong: ['Each router sends its full routing table to neighbors every 30 seconds', 'Routers trust the hop count their neighbors advertise', 'A central controller pushes routes to every router'],
    explain: 'OSPF is link state: everyone in the area shares a map and computes shortest paths. Periodic full tables are how distance-vector protocols like RIP work.',
    labs: ['ospf-single-area'],
  },
  {
    id: 'ospf-adjacency-mismatch',
    domain: '3.0',
    objective: '3.3.a',
    prompt: 'Two routers on the same subnet will not become OSPF neighbors. Which difference would cause that?',
    correct: ['Different hello and dead timers'],
    wrong: ['Different OSPF process IDs', 'Different interface priorities', 'Different router IDs'],
    explain: 'Area, subnet, hello/dead timers, authentication and stub flags must match. Process IDs are local, priorities only steer the DR election, and router IDs must differ.',
    labs: ['ospf-troubleshoot'],
  },
  {
    id: 'ospf-router-id',
    domain: '3.0',
    objective: '3.3.d',
    prompt: 'R1 has no router-id command, a loopback 10.0.0.1 and physical interfaces 192.168.1.1 and 172.16.1.1, all up. What is its OSPF router ID?',
    correct: ['10.0.0.1'],
    wrong: ['192.168.1.1', '172.16.1.1', '0.0.0.0'],
    explain: 'Order: the router-id command, then the highest loopback address, then the highest physical interface address. A loopback beats any physical interface.',
    labs: ['ospf-single-area'],
  },
  {
    id: 'ospf-rid-change',
    domain: '3.0',
    objective: '3.3.d',
    prompt: 'You change a running router’s OSPF router-id. When does the new ID take effect?',
    correct: ['After clear ip ospf process (or a reload)'],
    wrong: ['Immediately', 'After the next hello', 'Only after removing all network statements'],
    explain: 'IOS keeps the old router ID until the OSPF process is reset, and warns you so.',
    labs: ['ospf-single-area'],
  },
  {
    id: 'ospf-dr-election',
    domain: '3.0',
    objective: '3.3.c',
    prompt: 'Four routers share an Ethernet segment with default settings. How is the DR chosen?',
    correct: ['Highest interface priority, then highest router ID'],
    wrong: ['Lowest router ID', 'Lowest interface IP address', 'The first router to boot, always'],
    explain: 'Priority (default 1) decides first, then router ID. Priority 0 means never DR or BDR. The election is not preemptive once a DR exists.',
    labs: ['ospf-dr-bdr'],
  },
  {
    id: 'ospf-priority-zero',
    domain: '3.0',
    objective: '3.3.c',
    prompt: 'What does ip ospf priority 0 do on an interface?',
    correct: ['Stops the router from becoming DR or BDR on that segment'],
    wrong: ['Makes the router the DR', 'Disables OSPF on the interface', 'Sets the interface cost to 0'],
    explain: 'Priority 0 routers still form adjacencies with the DR and BDR, but never take either role.',
    labs: ['ospf-dr-bdr'],
  },
  {
    id: 'ospf-2way-normal',
    domain: '3.0',
    objective: '3.3.a',
    prompt: 'On a broadcast segment, show ip ospf neighbor on a DROTHER lists another DROTHER in state 2WAY. What does that mean?',
    correct: ['Normal: DROTHERs only go FULL with the DR and BDR'],
    wrong: ['Their hello timers do not match', 'The MTU differs on the two interfaces', 'One router is in the wrong area'],
    explain: 'Limiting full adjacencies to the DR and BDR cuts LSA flooding. 2WAY between DROTHERs is expected.',
    labs: ['ospf-dr-bdr'],
  },
  {
    id: 'ospf-p2p',
    domain: '3.0',
    objective: '3.3.b',
    prompt: 'You set ip ospf network point-to-point on both ends of a router-to-router Ethernet link. What changes?',
    correct: ['No DR or BDR is elected, so the adjacency forms faster'],
    wrong: ['The link stops sending hellos', 'The link’s cost doubles', 'The routers must be in different areas'],
    explain: 'With only two routers on the link, a DR adds nothing. Point-to-point skips the election and the wait timer.',
    labs: ['ospf-dr-bdr'],
  },
  {
    id: 'ospf-timers',
    domain: '3.0',
    objective: '3.3.a',
    prompt: 'What are the default OSPF hello and dead intervals on an Ethernet (broadcast) interface?',
    correct: ['10 seconds and 40 seconds'],
    wrong: ['30 seconds and 120 seconds', '5 seconds and 15 seconds', '60 seconds and 180 seconds'],
    explain: 'Broadcast and point-to-point networks default to 10/40. The dead interval is four hellos.',
    labs: ['ospf-troubleshoot'],
  },
  {
    id: 'ospf-reference-bw',
    domain: '3.0',
    objective: '3.3',
    prompt: 'OSPF gives a FastEthernet and a GigabitEthernet link the same cost of 1. Why, and what fixes it?',
    correct: ['The default reference bandwidth is 100 Mbps; raise it with auto-cost reference-bandwidth'],
    wrong: ['OSPF ignores bandwidth; use EIGRP instead', 'Both links have the same delay; change the delay', 'The cost is per hop; add more hops'],
    explain: 'Cost = reference bandwidth / interface bandwidth, never below 1. Set the same reference bandwidth on every router.',
  },
  {
    id: 'ospf-passive',
    domain: '3.0',
    objective: '3.3',
    prompt: 'What does passive-interface g0/1 do under router ospf 1?',
    correct: ['Stops OSPF hellos on G0/1 while still advertising its subnet'],
    wrong: ['Removes G0/1’s subnet from OSPF', 'Shuts G0/1 down', 'Makes G0/1 accept routes but not send them'],
    explain: 'Use it on LAN interfaces with no routers so nobody can form an adjacency there, while the LAN stays reachable.',
    labs: ['ospf-single-area'],
  },
  {
    id: 'ospf-network-wildcard',
    domain: '3.0',
    objective: '3.3',
    prompt: 'Which command enables OSPF in area 0 on the interface with address 10.1.1.1/24 and no other?',
    correct: ['network 10.1.1.1 0.0.0.0 area 0'],
    wrong: ['network 10.1.1.1 255.255.255.0 area 0', 'network 10.0.0.0 0.255.255.255 area 0', 'network 10.1.1.0 0.0.0.255 area 1'],
    explain: 'The network command uses a wildcard mask; 0.0.0.0 matches exactly one interface address. ip ospf 1 area 0 on the interface does the same.',
    labs: ['ospf-single-area'],
  },
  {
    id: 'ospf-multicast',
    domain: '3.0',
    objective: '3.3',
    prompt: 'To which address do OSPF routers send hellos on a broadcast network?',
    correct: ['224.0.0.5'],
    wrong: ['224.0.0.6', '224.0.0.10', '255.255.255.255'],
    explain: '224.0.0.5 reaches all OSPF routers; 224.0.0.6 reaches only the DR and BDR. 224.0.0.10 is EIGRP.',
  },
  {
    id: 'ospfv3-enable',
    domain: '3.0',
    objective: '3.3',
    prompt: 'How is OSPFv3 for IPv6 enabled on an interface in IOS?',
    correct: ['ipv6 ospf 1 area 0 in interface configuration'],
    wrong: ['network 2001:db8::/64 area 0 under ipv6 router ospf 1', 'ospfv3 enable in global configuration', 'ipv6 address 2001:db8::1/64 ospf'],
    explain: 'OSPFv3 has no network command; you enable it per interface. It also uses link-local addresses for neighbors.',
  },
  {
    id: 'hsrp-defaults',
    domain: '3.0',
    objective: '3.4',
    prompt: 'Two routers run HSRP with default settings. R1 was active, failed and has come back. Which router is active now?',
    correct: ['R2 stays active, because HSRP preemption is off by default'],
    wrong: ['R1, because it was active first', 'R1, because HSRP preemption is on by default', 'Both, sharing the load'],
    explain: 'Without standby preempt, a recovered higher-priority router waits as standby. VRRP, by contrast, preempts by default.',
    labs: ['hsrp-troubleshoot'],
  },
  {
    id: 'hsrp-show-standby',
    domain: '3.0',
    objective: '3.4',
    prompt: 'What does this output from R2 tell you?',
    exhibit: `R2# show standby brief
Interface   Grp  Pri P State   Active          Standby         Virtual IP
Gi0/0       10   110 P Standby 10.1.1.2        local           10.1.1.254`,
    correct: ['R2 is standby with priority 110 and preempt on; 10.1.1.2 is active'],
    wrong: ['R2 is active for 10.1.1.254', 'R2 has priority 100 and preemption off', 'The active router is 10.1.1.254'],
    explain: 'P means preempt. Since R2 has preempt and priority 110 but is still standby, the active router must have a higher priority (or a tie with a higher IP).',
    labs: ['hsrp-basic'],
  },
  {
    id: 'hsrp-track',
    domain: '3.0',
    objective: '3.4',
    prompt: 'The active HSRP router’s WAN link fails but it stays active, so traffic is black-holed. Which pair of settings fixes that?',
    correct: ['Track the WAN interface to lower priority on the active router, and enable preempt on the standby'],
    wrong: ['Raise the hello timer on both routers', 'Disable preempt on both routers', 'Use the same priority on both routers'],
    explain: 'Tracking drops the active router’s priority below its peer, and preempt lets the peer take over.',
    labs: ['hsrp-basic', 'hsrp-troubleshoot'],
  },
  {
    id: 'vrrp-standard',
    domain: '3.0',
    objective: '3.4',
    prompt: 'Which statement compares VRRP and HSRP correctly?',
    correct: ['VRRP is an open standard whose roles are master and backup; HSRP is Cisco proprietary with active and standby'],
    wrong: ['VRRP is Cisco proprietary; HSRP is the open standard', 'VRRP load-balances by default; HSRP does not', 'VRRP does not use a virtual IP address'],
    explain: 'Both give hosts one virtual gateway. GLBP is the one that balances hosts across several routers.',
    labs: ['vrrp-basic'],
  },
  {
    id: 'fhrp-virtual-mac',
    domain: '3.0',
    objective: '3.4',
    prompt: 'Which virtual MAC address belongs to HSRP version 1 group 10?',
    correct: ['0000.0c07.ac0a'],
    wrong: ['0000.5e00.010a', '0000.0c9f.f00a', '0007.b400.0a01'],
    explain: 'HSRPv1 uses 0000.0c07.acXX (group in hex), VRRP 0000.5e00.01XX, HSRPv2 0000.0c9f.fXXX and GLBP 0007.b400.XXYY.',
  },
  {
    id: 'glbp-avg',
    domain: '3.0',
    objective: '3.4',
    prompt: 'How does GLBP share hosts across several gateways?',
    correct: ['The AVG answers ARP for the virtual IP with different virtual MACs belonging to different AVFs'],
    wrong: ['Each router owns a different virtual IP', 'The active router forwards every packet and the others wait', 'Hosts are given several default gateways by DHCP'],
    explain: 'One active virtual gateway hands out up to four virtual MACs, so hosts keep one gateway address but spread across routers.',
    labs: ['glbp-load-balancing'],
  },
];
