import type { ExamQuestion } from '../types';

/** Domain 4.0: Network Services and Security. */
export const securityQuestions: ExamQuestion[] = [
  {
    id: 'tacacs-vs-radius',
    domain: '4.0',
    objective: '4.1',
    prompt: 'Which statement compares TACACS+ and RADIUS correctly?',
    correct: ['TACACS+ uses TCP 49 and encrypts the whole payload; RADIUS uses UDP and encrypts only the password'],
    wrong: ['RADIUS uses TCP 49 and encrypts everything; TACACS+ uses UDP', 'Both are Cisco proprietary', 'TACACS+ combines authentication and authorization; RADIUS separates them'],
    explain: 'TACACS+ (Cisco) separates authentication, authorization and accounting and suits device administration. RADIUS (open standard, UDP 1812/1813) combines authentication and authorization and suits network access.',
    labs: ['aaa-tacacs'],
  },
  {
    id: 'aaa-new-model',
    domain: '4.0',
    objective: '4.1',
    prompt: 'Which command must come first before you can define AAA method lists on IOS?',
    correct: ['aaa new-model'],
    wrong: ['aaa authentication enable', 'tacacs server', 'login local'],
    explain: 'aaa new-model switches the device from line passwords to AAA; it also immediately applies the default method list to all lines, so add a local user first.',
    labs: ['aaa-tacacs'],
  },
  {
    id: 'aaa-local-fallback',
    domain: '4.0',
    objective: '4.1',
    prompt: 'VTY logins use aaa authentication login default group radius local. The RADIUS server is up but rejects the user. What happens?',
    correct: ['The login fails; the local database is used only if the server does not answer'],
    wrong: ['The router tries the local user database next', 'The user gets privilege 1 access', 'The router retries RADIUS forever'],
    explain: 'Methods are tried in order only on an error (no response). An explicit reject is final.',
    labs: ['aaa-radius-troubleshoot'],
  },
  {
    id: 'local-user-secret',
    domain: '4.0',
    objective: '4.1',
    prompt: 'Which command creates a local user whose password is stored as a strong hash?',
    correct: ['username admin secret Str0ng!'],
    wrong: ['username admin password Str0ng!', 'enable password Str0ng!', 'line vty 0 15 password Str0ng!'],
    explain: 'secret stores a hash (type 5, 8 or 9). password stores plain text, or reversible type 7 with service password-encryption.',
    labs: ['ssh-remote-access'],
  },
  {
    id: 'password-encryption',
    domain: '4.0',
    objective: '4.1',
    prompt: 'What does service password-encryption do?',
    correct: ['Obscures plain-text passwords in the configuration with weak, reversible type 7 encoding'],
    wrong: ['Hashes every password with SHA-256', 'Encrypts the startup-config file', 'Forces SSH instead of Telnet'],
    explain: 'It only stops shoulder-surfing; type 7 is trivially reversed. Use secret for real protection.',
    labs: ['ssh-remote-access'],
  },
  {
    id: 'ssh-prereqs',
    domain: '4.0',
    objective: '4.1',
    prompt: 'crypto key generate rsa fails on a new switch. What does it need first?',
    correct: ['A hostname other than the default and an ip domain-name'],
    wrong: ['An enable secret', 'transport input ssh on the VTY lines', 'An SVI with an IP address'],
    explain: 'The RSA key is named after hostname.domain-name, so both must be set. VTY settings and addressing are needed later to actually log in.',
    labs: ['ssh-remote-access'],
  },
  {
    id: 'ssh-only-vty',
    domain: '4.0',
    objective: '4.1',
    prompt: 'Which VTY line commands allow only SSH logins checked against local usernames?',
    correct: ['login local and transport input ssh'],
    wrong: ['login and transport input all', 'password cisco and transport input telnet ssh', 'login local and transport output ssh'],
    explain: 'transport input controls which protocols may connect in; login local uses the username database. SSH uses TCP 22, Telnet TCP 23 in clear text.',
    labs: ['ssh-remote-access'],
  },
  {
    id: 'scp-needs-ssh',
    domain: '4.0',
    objective: '4.2',
    prompt: 'Which file transfer protocol copies configurations to or from an IOS device securely over SSH?',
    correct: ['SCP'],
    wrong: ['TFTP', 'FTP', 'HTTP'],
    explain: 'SCP (and SFTP) run inside SSH, so they are encrypted and authenticated. TFTP has no authentication at all; FTP sends credentials in clear text.',
    labs: ['config-backup'],
  },
  {
    id: 'tftp-facts',
    domain: '4.0',
    objective: '4.2',
    prompt: 'Which statement about TFTP is true?',
    correct: ['It uses UDP port 69 and has no authentication'],
    wrong: ['It uses TCP ports 20 and 21', 'It encrypts transfers with SSH', 'It lets you list and navigate server directories'],
    explain: 'TFTP is minimal: read or write one named file, with its own acknowledgements over UDP. FTP is the one with TCP 20/21, logins and directory commands.',
    labs: ['config-backup'],
  },
  {
    id: 'ftp-ports',
    domain: '4.0',
    objective: '4.2',
    prompt: 'Which ports does FTP use in active mode?',
    correct: ['TCP 21 for control and TCP 20 for data'],
    wrong: ['UDP 69 for both', 'TCP 22 for both', 'TCP 20 for control and TCP 21 for data'],
    explain: 'FTP keeps a control connection on TCP 21. In active mode the server opens data connections from TCP 20; in passive mode the client opens them to a port the server names.',
    labs: ['ftp-restore'],
  },
  {
    id: 'copy-running-startup',
    domain: '4.0',
    objective: '4.2',
    prompt: 'Where is the startup configuration kept on most Cisco routers?',
    correct: ['NVRAM'],
    wrong: ['RAM', 'ROM', 'A TFTP server'],
    explain: 'running-config lives in RAM and is lost on reload; copy running-config startup-config saves it to NVRAM. IOS images live in flash.',
    labs: ['config-backup'],
  },
  {
    id: 'nat-inside-local',
    domain: '4.0',
    objective: '4.3',
    prompt: 'In NAT terms, what is the inside local address?',
    correct: ['The private address of a host on the inside network'],
    wrong: ['The public address that represents the inside host', 'The address of a server on the internet', 'The router’s outside interface address'],
    explain: 'Inside local is the host’s real (usually private) address; inside global is the public address it is translated to.',
    labs: ['nat-static'],
  },
  {
    id: 'nat-static-cmd',
    domain: '4.0',
    objective: '4.3',
    prompt: 'Which command publishes the inside web server 192.168.1.10 as 203.0.113.10?',
    correct: ['ip nat inside source static 192.168.1.10 203.0.113.10'],
    wrong: ['ip nat outside source static 192.168.1.10 203.0.113.10', 'ip nat inside source static 203.0.113.10 192.168.1.10', 'ip nat pool WEB 203.0.113.10 192.168.1.10'],
    explain: 'Static NAT lists the inside local address first, then the inside global. Interfaces still need ip nat inside and ip nat outside.',
    labs: ['nat-static'],
  },
  {
    id: 'nat-pat',
    domain: '4.0',
    objective: '4.3',
    prompt: 'Which keyword lets many inside hosts share one public address by tracking port numbers?',
    correct: ['overload'],
    wrong: ['static', 'extendable', 'prefix-length'],
    explain: 'ip nat inside source list 1 interface g0/1 overload is PAT, the most common form of NAT on the internet edge.',
    labs: ['nat-pat'],
  },
  {
    id: 'nat-interfaces',
    domain: '4.0',
    objective: '4.3',
    prompt: 'PAT is configured with an ACL and overload, but show ip nat translations stays empty. What is the most likely omission?',
    correct: ['ip nat inside and ip nat outside on the interfaces'],
    wrong: ['ip routing', 'A static route for the inside network', 'service nat enable'],
    explain: 'NAT only considers traffic crossing from an inside-marked interface to an outside-marked one.',
    labs: ['nat-pat', 'capstone-branch-internet'],
  },
  {
    id: 'nat-pool-exhausted',
    domain: '4.0',
    objective: '4.3',
    prompt: 'Dynamic NAT (without overload) has a pool of 4 public addresses, all in use. What happens to a fifth inside host’s traffic?',
    correct: ['It is dropped until a translation times out'],
    wrong: ['It is sent untranslated', 'It shares an address using port numbers', 'It is translated to the router’s outside address'],
    explain: 'Dynamic NAT maps one inside address to one pool address. Only PAT shares addresses.',
  },
  {
    id: 'dns-aaaa',
    domain: '4.0',
    objective: '4.4',
    prompt: 'A user can reach www.example.com over IPv4 but not IPv6. Which DNS record would hold the site’s IPv6 address?',
    correct: ['AAAA'],
    wrong: ['A', 'PTR', 'CNAME'],
    explain: 'A records map names to IPv4 addresses, AAAA to IPv6. PTR maps addresses back to names; CNAME is an alias for another name.',
  },
  {
    id: 'dns-mx',
    domain: '4.0',
    objective: '4.4',
    prompt: 'Other organisations cannot deliver email to @example.com. Which record should you check first?',
    correct: ['The MX record for example.com'],
    wrong: ['The NS record for the mail server', 'The PTR record for the web server', 'The AAAA record for www.example.com'],
    explain: 'Senders look up MX records to find the mail servers for a domain, then resolve those names with A or AAAA records.',
  },
  {
    id: 'dns-cname',
    domain: '4.0',
    objective: '4.4',
    prompt: 'Which DNS record type makes shop.example.com an alias of a host named web1.example.com?',
    correct: ['CNAME'],
    wrong: ['A', 'MX', 'NS'],
    explain: 'A CNAME points one name at another canonical name, which then needs its own A or AAAA record.',
  },
  {
    id: 'dns-ptr',
    domain: '4.0',
    objective: '4.4',
    prompt: 'A server logs client addresses but you want their hostnames. Which record type answers a reverse lookup?',
    correct: ['PTR'],
    wrong: ['NS', 'A', 'CNAME'],
    explain: 'PTR records live in the in-addr.arpa (IPv4) and ip6.arpa (IPv6) zones and map addresses to names.',
  },
  {
    id: 'dns-ns',
    domain: '4.0',
    objective: '4.4',
    prompt: 'What does an NS record tell a resolver?',
    correct: ['Which servers are authoritative for a zone'],
    wrong: ['Which server handles mail for the zone', 'The zone’s IPv6 prefix', 'An alias for the zone apex'],
    explain: 'NS records delegate a zone to its authoritative name servers. DNS queries use UDP 53 (TCP 53 for large responses and zone transfers).',
  },
  {
    id: 'ipsec-tunnel-mode',
    domain: '4.0',
    objective: '4.5',
    prompt: 'In IPsec tunnel mode, what is protected?',
    correct: ['The whole original IP packet, which gets a new outer IP header'],
    wrong: ['Only the payload, keeping the original IP header', 'Only the outer IP header', 'Nothing; tunnel mode only adds routing'],
    explain: 'Site-to-site VPNs use tunnel mode between gateways. Transport mode keeps the original header and protects only the payload, typically between two end hosts.',
  },
  {
    id: 'ipsec-esp-ah',
    domain: '4.0',
    objective: '4.5',
    prompt: 'Which IPsec protocol provides encryption?',
    correct: ['ESP'],
    wrong: ['AH', 'IKE', 'GRE'],
    explain: 'ESP gives confidentiality, integrity and authentication. AH gives integrity and authentication only. IKE negotiates the keys; GRE is unencrypted tunneling.',
  },
  {
    id: 'vpn-remote-access',
    domain: '4.0',
    objective: '4.5',
    prompt: 'Which describes a remote-access VPN?',
    correct: ['Client software on one device builds a tunnel to the company’s VPN gateway, often with TLS or IPsec'],
    wrong: ['Two routers keep a permanent tunnel between two offices', 'An MPLS provider separates customers with labels', 'Branch users reach the internet through a proxy'],
    explain: 'Remote-access VPNs connect one end device on demand; site-to-site VPNs connect whole networks through their gateways, usually with IPsec.',
  },
  {
    id: 'acl-standard-match',
    domain: '4.0',
    objective: '4.6',
    prompt: 'What can a standard IPv4 ACL match on?',
    correct: ['Only the source IP address'],
    wrong: ['Source and destination addresses', 'Source address and destination port', 'Protocol and destination address'],
    explain: 'Standard ACLs (1 to 99, 1300 to 1999, or named standard) see only the source. Extended ACLs add protocol, destination and ports.',
    labs: ['acl-standard'],
  },
  {
    id: 'acl-standard-placement',
    domain: '4.0',
    objective: '4.6',
    prompt: 'Where should a standard ACL usually be applied?',
    correct: ['As close to the destination as possible'],
    wrong: ['As close to the source as possible', 'On every interface', 'Only on VTY lines'],
    explain: 'Because it only checks the source, a standard ACL near the source would block that host from everything. Extended ACLs go near the source to drop traffic early.',
    labs: ['acl-standard'],
  },
  {
    id: 'acl-implicit-deny',
    domain: '4.0',
    objective: '4.6',
    prompt: 'An ACL contains only "deny 10.1.1.0 0.0.0.255" and is applied inbound. What happens to traffic from 10.2.2.5?',
    correct: ['It is dropped by the implicit deny at the end of the list'],
    wrong: ['It is permitted because no line matches', 'It is permitted because the ACL only names 10.1.1.0', 'It is logged but forwarded'],
    explain: 'Every ACL ends with an invisible deny any. A list with only deny entries blocks everything; add permit any if that was intended.',
    labs: ['acl-troubleshoot'],
  },
  {
    id: 'acl-wildcard',
    domain: '4.0',
    objective: '4.6',
    prompt: 'Which wildcard mask matches every address in 172.16.32.0/20?',
    correct: ['0.0.15.255'],
    wrong: ['0.0.31.255', '255.255.240.0', '0.0.16.255'],
    explain: 'The wildcard is the inverse of the mask: 255.255.255.255 minus 255.255.240.0 = 0.0.15.255.',
    labs: ['acl-standard'],
  },
  {
    id: 'acl-extended-http',
    domain: '4.0',
    objective: '4.6',
    prompt: 'Which entry blocks web traffic to server 10.0.0.10 but not other traffic to it?',
    correct: ['deny tcp any host 10.0.0.10 eq 80'],
    wrong: ['deny ip any host 10.0.0.10', 'deny tcp host 10.0.0.10 any eq 80', 'deny udp any host 10.0.0.10 eq 80'],
    explain: 'Extended entries read protocol, source, destination, then the port. HTTP is TCP 80 to the server.',
    labs: ['acl-extended'],
  },
  {
    id: 'acl-delete-entry',
    domain: '4.0',
    objective: '4.6',
    prompt: 'How do you remove just the entry with sequence number 30 from ACL 101?',
    correct: ['In ip access-list extended 101 mode, enter no 30'],
    wrong: ['no access-list 101 deny tcp any any eq 80 in global configuration', 'no access-list 101 30', 'You must delete and rebuild the whole list'],
    explain: 'Named-ACL configuration mode works for numbered lists too and edits by sequence number. no access-list 101 ... in global configuration deletes the entire ACL.',
    labs: ['acl-troubleshoot'],
  },
  {
    id: 'acl-per-interface',
    domain: '4.0',
    objective: '4.6',
    prompt: 'How many IPv4 ACLs can be applied to one interface?',
    correct: ['One per direction: one inbound and one outbound'],
    wrong: ['One in total', 'Unlimited, processed in order', 'Two per direction'],
    explain: 'Applying a second ACL in the same direction replaces the first.',
    labs: ['acl-extended'],
  },
  {
    id: 'acl-numbered-ranges',
    domain: '4.0',
    objective: '4.6',
    prompt: 'access-list 150 permit ip any any creates which kind of ACL?',
    correct: ['An extended ACL'],
    wrong: ['A standard ACL', 'An IPv6 ACL', 'An ARP ACL'],
    explain: 'Numbers 1 to 99 and 1300 to 1999 are standard; 100 to 199 and 2000 to 2699 are extended.',
  },
  {
    id: 'dhcp-snooping-untrusted',
    domain: '4.0',
    objective: '4.7',
    prompt: 'DHCP snooping is enabled. Which message arriving on an untrusted port is dropped?',
    correct: ['DHCPOFFER'],
    wrong: ['DHCPDISCOVER', 'DHCPREQUEST', 'DHCPRELEASE from the client that holds the lease'],
    explain: 'Server messages (OFFER, ACK, NAK) are only accepted on trusted ports, which stops rogue DHCP servers. Trust the uplink toward the real server.',
    labs: ['dhcp-snooping'],
  },
  {
    id: 'dhcp-snooping-option82',
    domain: '4.0',
    objective: '4.7',
    prompt: 'After enabling DHCP snooping on an access switch, clients behind it stop getting leases from an IOS DHCP server reached through a relay. What is a common cause?',
    correct: ['The switch inserts option 82 and the server rejects it; use no ip dhcp snooping information option'],
    wrong: ['DHCP snooping blocks all DISCOVER messages', 'The relay must be configured as an untrusted port', 'Snooping requires a static binding for every client'],
    explain: 'By default the switch adds option 82 with a zero giaddr, which many servers drop.',
    labs: ['dhcp-snooping-troubleshoot'],
  },
  {
    id: 'dai-binding',
    domain: '4.0',
    objective: '4.7',
    prompt: 'What does Dynamic ARP Inspection check ARP packets on untrusted ports against?',
    correct: ['The DHCP snooping binding table (and any ARP ACLs)'],
    wrong: ['The MAC address table', 'The routing table', 'The CDP neighbor table'],
    explain: 'DAI drops ARP messages whose IP-to-MAC pairing is not in the snooping bindings, which stops ARP poisoning.',
    labs: ['dynamic-arp-inspection'],
  },
  {
    id: 'dai-static-host',
    domain: '4.0',
    objective: '4.7',
    prompt: 'After DAI is enabled, a server with a static IP address loses connectivity while DHCP clients are fine. What should you add?',
    correct: ['An ARP ACL permitting the server’s IP and MAC, applied with ip arp inspection filter'],
    wrong: ['ip dhcp snooping trust on the server’s port and nothing else', 'A static MAC address table entry', 'ip arp inspection validate src-mac'],
    explain: 'A static host never appears in the snooping table, so DAI has no binding for it. An ARP ACL (or trusting the port) lets it through.',
    labs: ['dai-arp-acl'],
  },
  {
    id: 'port-security-defaults',
    domain: '4.0',
    objective: '4.7',
    prompt: 'You enter switchport port-security on an access port and nothing else. What are the defaults?',
    correct: ['One MAC address allowed, violation mode shutdown'],
    wrong: ['Unlimited MAC addresses, violation mode protect', 'One MAC address allowed, violation mode restrict', 'Two MAC addresses allowed, violation mode shutdown'],
    explain: 'A second MAC on the port err-disables it. Raise the limit with switchport port-security maximum.',
    labs: ['port-security'],
  },
  {
    id: 'port-security-restrict',
    domain: '4.0',
    objective: '4.7',
    prompt: 'What is the difference between the restrict and protect violation modes?',
    correct: ['Both drop offending frames, but restrict also logs and counts violations'],
    wrong: ['Restrict err-disables the port; protect does not', 'Protect logs violations; restrict silently drops', 'Restrict allows the frames but logs them'],
    explain: 'Shutdown err-disables the port; restrict drops and records; protect drops silently.',
    labs: ['port-security'],
  },
  {
    id: 'port-security-dynamic',
    domain: '4.0',
    objective: '4.7',
    prompt: 'switchport port-security is rejected on a port left at its default dynamic DTP mode. Why?',
    correct: ['Port security needs the port statically set to access (or trunk)'],
    wrong: ['Port security only works on routed ports', 'The port must first be shut down', 'Port security needs DHCP snooping'],
    explain: 'Set switchport mode access first. A port that might negotiate a trunk cannot have port security.',
    labs: ['port-security'],
  },
  {
    id: 'errdisable-recover',
    domain: '4.0',
    objective: '4.7',
    prompt: 'A port is err-disabled after a port security violation. You have removed the rogue device. How do you bring the port back by hand?',
    correct: ['shutdown, then no shutdown on the interface'],
    wrong: ['clear port-security on the interface only', 'no switchport port-security violation', 'Reload the switch; nothing else works'],
    explain: 'Bouncing the port clears err-disabled. errdisable recovery cause psecure-violation can do it automatically after an interval.',
    labs: ['port-security-errdisable'],
  },
  {
    id: 'storm-control',
    domain: '4.0',
    objective: '4.7',
    prompt: 'What does storm-control broadcast level 20 do on an interface?',
    correct: ['Drops broadcast traffic above 20% of the port’s bandwidth'],
    wrong: ['Err-disables the port after 20 broadcasts', 'Limits the port to 20 MAC addresses', 'Rate-limits all traffic to 20 Mbps'],
    explain: 'Storm control suppresses broadcast, multicast or unknown unicast past a threshold; storm-control action shutdown or trap changes what happens.',
    labs: ['storm-control'],
  },
  {
    id: 'ra-guard',
    domain: '4.0',
    objective: '4.7',
    prompt: 'A user’s laptop starts sending IPv6 Router Advertisements and hosts pick it as their gateway. Which switch feature stops this?',
    correct: ['RA guard on host-facing ports'],
    wrong: ['DHCP snooping', 'BPDU guard', 'Dynamic ARP Inspection'],
    explain: 'RA guard drops Router Advertisements arriving on ports whose policy says the attached device is a host.',
    labs: ['ra-guard'],
  },
  {
    id: 'qos-ef',
    domain: '4.0',
    objective: '4.0',
    prompt: 'Which DSCP value marks voice as Expedited Forwarding?',
    correct: ['46'],
    wrong: ['34', '26', '0'],
    explain: 'EF is 46. AF41 is 34, AF31 is 26, and 0 is best effort (default).',
    labs: ['qos-marking'],
  },
  {
    id: 'qos-llq',
    domain: '4.0',
    objective: '4.0',
    prompt: 'Which queuing method gives voice a strict-priority queue while other classes share the remaining bandwidth?',
    correct: ['LLQ (low latency queuing)'],
    wrong: ['FIFO', 'Weighted random early detection', 'Policing'],
    explain: 'LLQ is CBWFQ plus a priority queue, configured with the priority command in a policy map. The priority queue is policed so it cannot starve the rest.',
    labs: ['qos-marking'],
  },
  {
    id: 'qos-shape-police',
    domain: '4.0',
    objective: '4.0',
    prompt: 'What is the difference between policing and shaping?',
    correct: ['Policing drops or re-marks traffic over the rate; shaping buffers it and sends it later'],
    wrong: ['Shaping drops excess traffic; policing buffers it', 'Both buffer traffic, but policing uses more memory', 'Policing only works inbound and shaping only outbound on every platform'],
    explain: 'An ISP often polices to the contracted rate, so the customer shapes outbound to stay under it.',
  },
  {
    id: 'qos-trust-boundary',
    domain: '4.0',
    objective: '4.0',
    prompt: 'Voice packets leave the IP phone marked EF but arrive at the router marked 0. What is the likely cause?',
    correct: ['The access switch port does not trust the phone’s markings and rewrites them'],
    wrong: ['The router’s policy map is missing a priority queue', 'The phone is in the data VLAN', 'EF is not a valid DSCP value'],
    explain: 'With mls qos enabled, ports are untrusted by default and reset markings. Extend the trust boundary to the phone with mls qos trust (and trust device cisco-phone).',
    labs: ['qos-trust-boundary'],
  },
];
