import type { ExamQuestion } from '../types';

/** Domain 2.0: Switching and Network Access. */
export const switchingQuestions: ExamQuestion[] = [
  {
    id: 'switch-unknown-unicast',
    domain: '2.0',
    objective: '2.4',
    prompt: 'A switch receives a frame whose destination MAC address is not in its MAC address table. What does it do?',
    correct: ['Floods it out every port in the same VLAN except the one it arrived on'],
    wrong: ['Drops it', 'Sends an ARP request for the destination', 'Forwards it to the default gateway only'],
    explain: 'Unknown unicast is flooded within the VLAN. The switch learns the source MAC from every frame, so the reply fills in the table.',
    labs: ['vlans-basic'],
  },
  {
    id: 'switch-learns-source',
    domain: '2.0',
    objective: '2.4',
    prompt: 'Which address does a switch use to build its MAC address table?',
    correct: ['The source MAC address of frames it receives'],
    wrong: ['The destination MAC address of frames it receives', 'The source IP address of packets', 'MAC addresses announced by CDP'],
    explain: 'Switches learn where a MAC lives from the source field and the arriving port, then forward by looking up the destination.',
  },
  {
    id: 'vlan-default',
    domain: '2.0',
    objective: '2.2',
    prompt: 'Out of the box, which VLAN are all the access ports on a Cisco switch in?',
    correct: ['VLAN 1'],
    wrong: ['VLAN 0', 'VLAN 99', 'No VLAN until one is assigned'],
    explain: 'Every port starts in VLAN 1, which also cannot be deleted. Best practice moves user ports and the native VLAN off it.',
    labs: ['vlans-basic'],
  },
  {
    id: 'dot1q-tag',
    domain: '2.0',
    objective: '2.1',
    prompt: 'What does an 802.1Q trunk add to a frame, and how large is the VLAN ID field?',
    correct: ['A 4-byte tag with a 12-bit VLAN ID'],
    wrong: ['A 26-byte header with a 10-bit VLAN ID', 'A 4-byte tag with a 16-bit VLAN ID', 'A 2-byte tag with an 8-bit VLAN ID'],
    explain: 'The 802.1Q tag is 4 bytes: TPID 0x8100, then 3 PCP bits, 1 DEI bit and a 12-bit VID (0 to 4095, with 0 and 4095 reserved). The 26-byte header is ISL.',
    labs: ['trunk-two-switches'],
  },
  {
    id: 'native-vlan-untagged',
    domain: '2.0',
    objective: '2.1',
    prompt: 'How does an 802.1Q trunk send frames that belong to its native VLAN?',
    correct: ['Untagged'],
    wrong: ['Tagged with VLAN 0', 'Tagged with VLAN 1', 'Encapsulated in ISL'],
    explain: 'Native VLAN traffic crosses the trunk without a tag, and untagged frames received are placed in the native VLAN. Both ends must agree on it.',
    labs: ['trunk-two-switches'],
  },
  {
    id: 'native-vlan-mismatch',
    domain: '2.0',
    objective: '2.3',
    prompt: 'A switch logs "%CDP-4-NATIVE_VLAN_MISMATCH". What is wrong?',
    correct: ['The two ends of a trunk use different native VLANs'],
    wrong: ['One end of the link is an access port in the wrong VLAN', 'CDP is disabled on the neighbor', 'The trunk is missing an allowed VLAN'],
    explain: 'CDP advertises the native VLAN and complains when the neighbor differs. Untagged traffic would otherwise leak between the two VLANs.',
    labs: ['cdp-native-vlan'],
  },
  {
    id: 'trunk-allowed',
    domain: '2.0',
    objective: '2.1',
    prompt: 'Which interface command limits a trunk to carrying only VLANs 10 and 20?',
    correct: ['switchport trunk allowed vlan 10,20'],
    wrong: ['switchport trunk native vlan 10,20', 'switchport access vlan 10,20', 'vlan 10,20 trunk'],
    explain: 'The allowed list filters which VLANs cross the trunk. Use "allowed vlan add" to append rather than replace the list.',
    labs: ['trunk-two-switches'],
  },
  {
    id: 'roas-subinterface',
    domain: '2.0',
    objective: '2.1',
    prompt: 'On a router-on-a-stick, which command ties subinterface G0/0.10 to VLAN 10?',
    correct: ['encapsulation dot1q 10'],
    wrong: ['switchport access vlan 10', 'vlan 10', 'ip vlan 10'],
    explain: 'Each subinterface needs encapsulation dot1q with its VLAN ID before it accepts an IP address. Add "native" for the native VLAN.',
    labs: ['router-on-a-stick'],
  },
  {
    id: 'svi-ip-routing',
    domain: '2.0',
    objective: '2.1',
    prompt: 'A multilayer switch has SVIs for VLANs 10 and 20, both up, but hosts in the two VLANs cannot reach each other. What is missing?',
    correct: ['ip routing'],
    wrong: ['A trunk between the SVIs', 'encapsulation dot1q on each SVI', 'spanning-tree portfast'],
    explain: 'SVIs give each VLAN a gateway address, but a Layer 3 switch only routes between them once ip routing is enabled globally.',
    labs: ['l3-switch-svi'],
  },
  {
    id: 'switch-default-gateway',
    domain: '2.0',
    objective: '2.1',
    prompt: 'A Layer 2 switch has a management SVI and answers pings from its own subnet but not from other subnets. What should you add?',
    correct: ['ip default-gateway pointing at the subnet’s router'],
    wrong: ['ip routing', 'A static route on the PCs', 'spanning-tree vlan 1 root primary'],
    explain: 'A Layer 2 switch does not route, so it needs ip default-gateway to send replies off its own subnet.',
    labs: ['switch-management'],
  },
  {
    id: 'voice-vlan',
    domain: '2.0',
    objective: '2.2',
    prompt: 'An IP phone with a PC plugged into it connects to an access port configured with switchport access vlan 10 and switchport voice vlan 20. How does the traffic arrive?',
    correct: ['PC traffic untagged in VLAN 10, phone traffic tagged with VLAN 20'],
    wrong: ['Both untagged in VLAN 10', 'Both tagged, because the port becomes a trunk', 'Phone traffic untagged in VLAN 20, PC traffic tagged with VLAN 10'],
    explain: 'The phone has a small internal switch. It tags its own voice frames with the voice VLAN and passes the PC’s frames untagged.',
  },
  {
    id: 'dtp-auto-auto',
    domain: '2.0',
    objective: '2.1',
    prompt: 'Both ends of a link are set to switchport mode dynamic auto. What does the link become?',
    correct: ['An access link'],
    wrong: ['A trunk', 'Err-disabled', 'A trunk carrying only the native VLAN'],
    explain: 'Dynamic auto only answers DTP, it never starts negotiation, so two auto ports stay access. Hard-code trunks and use switchport nonegotiate instead.',
  },
  {
    id: 'vtp-transparent',
    domain: '2.0',
    objective: '2.1',
    prompt: 'What does a switch in VTP transparent mode do with VTP advertisements?',
    correct: ['Forwards them on trunks but does not apply them to its own VLAN database'],
    wrong: ['Applies them and forwards them', 'Drops them', 'Applies them but does not forward them'],
    explain: 'Transparent switches keep their own VLANs and revision number 0, which is why many networks run every switch in transparent mode or VTP off.',
  },
  {
    id: 'lacp-modes',
    domain: '2.0',
    objective: '2.1',
    prompt: 'Which pair of channel-group modes forms an LACP EtherChannel?',
    correct: ['active and passive'],
    wrong: ['passive and passive', 'desirable and auto', 'on and active'],
    explain: 'LACP needs at least one active side. Passive and passive never start negotiation; desirable and auto are PAgP; "on" does not negotiate at all.',
    labs: ['etherchannel-lacp'],
  },
  {
    id: 'etherchannel-mismatch',
    domain: '2.0',
    objective: '2.1',
    prompt: 'One port in a channel-group shows as suspended (s) in show etherchannel summary. What is the usual cause?',
    correct: ['Its settings, such as speed, duplex or VLAN configuration, differ from the other members'],
    wrong: ['The port-channel interface was shut down', 'It is the backup link, which LACP keeps idle', 'Spanning tree blocked the port-channel'],
    explain: 'All members must match speed, duplex, mode (access or trunk), access VLAN or allowed VLANs and native VLAN, or the odd one out is suspended.',
    labs: ['etherchannel-troubleshoot'],
  },
  {
    id: 'etherchannel-loadbalance',
    domain: '2.0',
    objective: '2.1',
    prompt: 'A single large file transfer between two hosts crosses a four-link EtherChannel. How much of the bundle does it use?',
    correct: ['One member link, because load balancing hashes each flow to one link'],
    wrong: ['All four links, sending packets round-robin', 'Two links, one in each direction', 'The fastest link only, chosen by STP'],
    explain: 'EtherChannel picks a link per flow from a hash of addresses or ports, which keeps frames in order. Many flows spread out; one flow does not.',
  },
  {
    id: 'cdp-vs-lldp',
    domain: '2.0',
    objective: '2.3',
    prompt: 'You need to discover neighbors in a network that mixes Cisco and other vendors. Which protocol should you use?',
    correct: ['LLDP, the IEEE 802.1AB standard'],
    wrong: ['CDP, because every vendor supports it', 'STP', 'VTP'],
    explain: 'CDP is Cisco proprietary. LLDP is the open standard; on Cisco IOS it is off by default and enabled with lldp run.',
    labs: ['cdp-lldp-map'],
  },
  {
    id: 'lldp-default',
    domain: '2.0',
    objective: '2.3',
    prompt: 'What is the default state of CDP and LLDP on most Cisco IOS switches?',
    correct: ['CDP is enabled and LLDP is disabled'],
    wrong: ['Both are enabled', 'Both are disabled', 'LLDP is enabled and CDP is disabled'],
    explain: 'CDP runs globally by default. LLDP needs lldp run (and can be tuned per interface with lldp transmit and lldp receive).',
    labs: ['cdp-lldp-map'],
  },
  {
    id: 'cdp-timers',
    domain: '2.0',
    objective: '2.3',
    prompt: 'What are the default CDP advertisement interval and holdtime?',
    correct: ['60 seconds and 180 seconds'],
    wrong: ['30 seconds and 120 seconds', '10 seconds and 40 seconds', '2 seconds and 6 seconds'],
    explain: 'CDP sends every 60 s and forgets a neighbor after 180 s of silence. show cdp displays both timers. LLDP defaults to 30 s and 120 s.',
  },
  {
    id: 'cdp-detail',
    domain: '2.0',
    objective: '2.3',
    prompt: 'Which command shows a CDP neighbor’s management IP address and software version?',
    correct: ['show cdp neighbors detail'],
    wrong: ['show cdp neighbors', 'show cdp interface', 'show lldp'],
    explain: 'The summary table lists device ID, ports, platform and capabilities. The detail view adds addresses and the IOS version.',
    labs: ['cdp-lldp-map'],
  },
  {
    id: 'stp-root-election',
    domain: '2.0',
    objective: '2.5',
    prompt: 'How is the spanning tree root bridge elected?',
    correct: ['Lowest bridge ID: priority first, then the lowest MAC address'],
    wrong: ['Highest bridge ID', 'Lowest total path cost', 'The switch with the most ports'],
    explain: 'Every switch first claims to be root; the lowest priority wins, and the lowest MAC breaks a tie. Set the priority so the choice is deliberate.',
    labs: ['stp-root-bridge'],
  },
  {
    id: 'stp-priority-sysid',
    domain: '2.0',
    objective: '2.5',
    prompt: 'A switch has the default bridge priority. What priority does show spanning-tree report for VLAN 10?',
    correct: ['32778'],
    wrong: ['32768', '4096', '32769'],
    explain: 'PVST+ adds the VLAN ID (the extended system ID) to the configured priority: 32768 + 10 = 32778.',
    labs: ['stp-root-bridge'],
  },
  {
    id: 'stp-root-primary',
    domain: '2.0',
    objective: '2.5',
    prompt: 'What does spanning-tree vlan 10 root primary do?',
    correct: ['Sets this switch’s VLAN 10 priority low enough to become root'],
    wrong: ['Makes the port connected to the root a root port', 'Disables STP on VLAN 10', 'Locks the current root so no other switch can take over'],
    explain: 'The macro sets priority 24576, or lower if another switch already beats that. It does not stop a lower priority from taking over later; root guard does that.',
    labs: ['stp-root-bridge'],
  },
  {
    id: 'stp-cost-100',
    domain: '2.0',
    objective: '2.5',
    prompt: 'Using the default short path-cost method, what is the STP cost of a 100 Mbps link?',
    correct: ['19'],
    wrong: ['4', '100', '2'],
    explain: 'Short costs: 10 Mbps = 100, 100 Mbps = 19, 1 Gbps = 4, 10 Gbps = 2.',
  },
  {
    id: 'rstp-states',
    domain: '2.0',
    objective: '2.5',
    prompt: 'Which port states does Rapid PVST+ use?',
    correct: ['Discarding, learning and forwarding'],
    wrong: ['Blocking, listening, learning and forwarding', 'Disabled, listening and forwarding', 'Discarding, listening and forwarding'],
    explain: 'RSTP merges disabled, blocking and listening into discarding. Classic 802.1D has blocking, listening, learning and forwarding.',
    labs: ['stp-root-bridge'],
  },
  {
    id: 'rstp-alternate',
    domain: '2.0',
    objective: '2.5',
    prompt: 'In Rapid PVST+, what is an alternate port?',
    correct: ['A discarding port with a backup path to the root, ready to replace the root port'],
    wrong: ['A port that is forwarding toward a segment with no other switch', 'A port connected to an end host', 'A second root port that load-balances'],
    explain: 'Alternate ports receive superior BPDUs from another switch and take over immediately if the root port fails. Backup ports back up a designated port on a shared segment.',
    labs: ['stp-root-bridge'],
  },
  {
    id: 'portfast',
    domain: '2.0',
    objective: '2.5',
    prompt: 'What does PortFast do on an access port?',
    correct: ['Moves the port straight to forwarding when it comes up'],
    wrong: ['Disables STP on the whole VLAN', 'Raises the port speed to the maximum', 'Bundles the port into an EtherChannel'],
    explain: 'PortFast skips the listening and learning delay so hosts get connectivity quickly. Use it only where a single end device connects.',
    labs: ['stp-portfast-bpduguard'],
  },
  {
    id: 'bpdu-guard',
    domain: '2.0',
    objective: '2.5',
    prompt: 'Someone plugs a switch into a port with BPDU guard enabled. What happens?',
    correct: ['The port is err-disabled as soon as it receives a BPDU'],
    wrong: ['The port keeps forwarding but ignores BPDUs', 'The new switch becomes root for that port only', 'The port moves to the root-inconsistent state'],
    explain: 'BPDU guard protects PortFast edge ports. Root-inconsistent is what root guard does.',
    labs: ['stp-portfast-bpduguard'],
  },
  {
    id: 'root-guard',
    domain: '2.0',
    objective: '2.5',
    prompt: 'What does root guard protect against?',
    correct: ['A switch on that port becoming the root bridge'],
    wrong: ['A unidirectional link turning an alternate port into a designated port', 'Hosts sending too many broadcasts', 'BPDUs arriving on a PortFast port'],
    explain: 'If a superior BPDU arrives on a root-guard port, the port goes root-inconsistent until the BPDUs stop. Loop guard handles unidirectional links.',
  },
  {
    id: 'loop-guard',
    domain: '2.0',
    objective: '2.5',
    prompt: 'A fiber link becomes unidirectional and a root or alternate port stops receiving BPDUs. Which feature stops that port from moving to forwarding?',
    correct: ['Loop guard'],
    wrong: ['Root guard', 'BPDU filter', 'PortFast'],
    explain: 'Loop guard puts the port in loop-inconsistent (blocking) instead of letting it become designated and create a loop.',
  },
  {
    id: 'capwap',
    domain: '2.0',
    objective: '2.2',
    prompt: 'Which protocol do lightweight APs use to talk to their wireless LAN controller?',
    correct: ['CAPWAP, with separate control and data tunnels'],
    wrong: ['LWAPP over TCP', 'GRE with no control channel', 'IPsec tunnel mode'],
    explain: 'CAPWAP uses UDP 5246 for control (always DTLS-encrypted) and UDP 5247 for client data.',
    labs: ['ap-join-option43'],
  },
  {
    id: 'ap-option43',
    domain: '2.0',
    objective: '2.2',
    prompt: 'Lightweight APs are in a different subnet from the WLC and cannot find it. What can the DHCP server give them?',
    correct: ['Option 43 with the controller’s management address'],
    wrong: ['Option 66 with a TFTP server', 'Option 82 with the switch port', 'Option 150 with a call manager'],
    explain: 'DHCP option 43 carries WLC addresses to APs. A DNS entry for CISCO-CAPWAP-CONTROLLER is the other common method.',
    labs: ['ap-join-option43'],
  },
  {
    id: 'ap-flexconnect',
    domain: '2.0',
    objective: '2.2',
    prompt: 'Branch APs must keep serving clients locally even if the WAN link to the central WLC fails. Which AP mode fits?',
    correct: ['FlexConnect'],
    wrong: ['Local', 'Sniffer', 'Monitor'],
    explain: 'FlexConnect APs can switch traffic locally and keep working when the controller is unreachable. Local mode tunnels everything to the WLC.',
  },
  {
    id: 'ap-switchport',
    domain: '2.0',
    objective: '2.2',
    prompt: 'How should the switch port for a lightweight AP in local mode normally be configured?',
    correct: ['As an access port in the AP management VLAN'],
    wrong: ['As a trunk carrying every WLAN’s VLAN', 'As a routed port', 'As an EtherChannel member'],
    explain: 'In local mode all client traffic goes through the CAPWAP tunnel to the WLC, so the AP only needs one VLAN. Autonomous and FlexConnect APs bridging several VLANs need trunks.',
    labs: ['wlan-wpa2-psk'],
  },
  {
    id: 'extended-ping',
    domain: '2.0',
    objective: '2.4',
    prompt: 'You want to test whether a remote network has a route back to R1’s LAN interface. Which tool lets you set the source of a ping from R1?',
    correct: ['An extended ping (ping with the source option)'],
    wrong: ['A standard ping', 'show ip route', 'show cdp neighbors'],
    explain: 'A normal ping is sourced from the exit interface. Sourcing it from the LAN address proves the return path to that subnet too.',
  },
  {
    id: 'traceroute-mechanism',
    domain: '2.0',
    objective: '2.4',
    prompt: 'How does traceroute discover each router along the path?',
    correct: ['It sends probes with increasing TTL values and lists who returns ICMP Time Exceeded'],
    wrong: ['Each router adds its address to the packet as it passes', 'It asks each router for its routing table', 'It uses CDP to find the next hop'],
    explain: 'A probe with TTL 1 expires at the first router, TTL 2 at the second, and so on, until the destination answers.',
    labs: ['fix-the-office'],
  },
];
